project/mysite/myapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'myapp'
urlpatterns = [
    url(r'^home/$', views.home, name = 'home'),
    url(r'^map/$', views.map, name = 'map'),
    url(r'^presentation/$', views.presentation, name = 'presentation'),
    url(r'^about/$', views.about, name = 'about'),
    url(r'^csv/$', views.csv),
    url(r'^csv/(?P<station>[0-9]+)/$', views.csv),
    url(r'^pic/(?P<station>[0-9]+)/$', views.pic, name='pic'),
    url(r'^plot/$', views.plot, name='plot'),
]

project/mysite/mysite/urls.py
from django.conf.urls import url
from django.conf.urls import include

urlpatterns = [
    url(r'^myapp/', include('myapp.urls')),
]

project/mysite/myapp/models.py
from django.db import models

# Create your models here.

STATION = (  
    ('156', 'Clark St & Wellington Ave'),
    ('303', 'Broadway & Cornelia Ave'),
    ('295', 'Broadway & Argyle St'),
    ('419', 'Lake Park Ave & 53rd St'),
    ('191', 'Canal St & Monroe St (*)'),
    ('374', 'Western Ave & Walton St'),
    ('148', 'State St & 33rd St'),
    ('30', 'Ashland Ave & Augusta Blvd'),
    ('359', 'Larrabee St & Division St'),
    ('110', 'Dearborn St & Erie St'),
    ('98', 'LaSalle St & Washington St'),
    ('220', 'Hampden Ct & Diversey Pkwy'),
    ('87', 'Racine Ave & Fullerton Ave'),
    ('282', 'Halsted St & Maxwell St'),
    ('293', 'Broadway & Wilson Ave'),
    ('243', 'Lincoln Ave & Leavitt St'),
    ('364', 'Larrabee St & Oak St'),
    ('423', 'University Ave & 57th St'),
    ('120', 'Wentworth Ave & Archer Ave'),
    ('135', 'Halsted St & 21st St'),
    ('131', 'Lincoln Ave & Belmont Ave'),
    ('56', 'Desplaines St & Kinzie St'),
    ('118', 'Sedgwick St & North Ave'),
    ('57', 'Clinton St & Roosevelt Rd'),
    ('198', 'Green St & Madison St'),
    ('321', 'Wabash Ave & 8th St'),
    ('296', 'Broadway & Belmont Ave'),
    ('312', 'Clarendon Ave & Gordon Ter'),
    ('119', 'Ashland Ave & Lake St'),
    ('217', 'May St & Fulton St'),
    ('49', 'Dearborn St & Monroe St'),
    ('376', 'Artesian Ave & Hubbard St'),
    ('127', 'Lincoln Ave & Fullerton Ave'),
    ('133', 'Kingsbury St & Kinzie St'),
    ('458', 'Broadway & Thorndale Ave'),
    ('212', 'Orleans St & Ohio St'),
    ('181', 'LaSalle St & Illinois St'),
    ('190', 'Southport Ave & Wrightwood Ave'),
    ('465', 'Marine Dr & Ainslie St'),
    ('394', 'Clark St & 9th St (AMLI)'),
    ('144', 'Larrabee St & Webster Ave'),
    ('92', 'Carpenter St & Huron St'),
    ('96', 'Desplaines St & Randolph St'),
    ('43', 'Michigan Ave & Washington St'),
    ('350', 'Ashland Ave & Chicago Ave'),
    ('337', 'Clark St & Chicago Ave'),
    ('382', 'Western Ave & Congress Pkwy'),
    ('21', 'Aberdeen St & Jackson Blvd'),
    ('31', 'Franklin St & Chicago Ave'),
    ('242', 'Damen Ave & Leland Ave'),
    ('245', 'Clarendon Ave & Junior Ter'),
    ('192', 'Canal St & Adams St'),
    ('322', 'Kimbark Ave & 53rd St'),
    ('254', 'Pine Grove Ave & Irving Park Rd'),
    ('174', 'Canal St & Madison St'),
    ('71', 'Morgan St & Lake St'),
    ('80', 'Aberdeen St & Monroe St'),
    ('153', 'Southport Ave & Wellington Ave'),
    ('349', 'Halsted St & Wrightwood Ave'),
    ('46', 'Wells St & Walton St'),
    ('152', 'Lincoln Ave & Diversey Pkwy'),
    ('171', 'May St & Cullerton St'),
    ('106', 'State St & Pearson St'),
    ('74', 'Kingsbury St & Erie St'),
    ('68', 'Clinton St & Tilden St'),
    ('290', 'Kedzie Ave & Palmer Ct'),
    ('52', 'Michigan Ave & Lake St'),
    ('214', 'Damen Ave & Grand Ave'),
    ('16', 'Paulina Ave & North Ave'),
    ('114', 'Sheffield Ave & Addison St'),
    ('134', 'Peoria St & Jackson Blvd'),
    ('478', 'Rockwell St & Eastwood Ave'),
    ('66', 'Clinton St & Lake St'),
    ('125', 'Rush St & Hubbard St'),
    ('137', 'Morgan Ave & 14th Pl'),
    ('291', 'Wells St & Evergreen Ave'),
    ('278', 'Wallace St & 35th St'),
    ('36', 'Franklin St & Jackson Blvd'),
    ('26', 'McClurg Ct & Illinois St'),
    ('227', 'Southport Ave & Waveland Ave'),
    ('89', 'Financial Pl & Congress Pkwy'),
    ('142', 'McClurg Ct & Erie St'),
    ('261', 'Hermitage Ave & Polk St'),
    ('460', 'Clark St & Bryn Mawr Ave'),
    ('33', 'State St & Van Buren St'),
    ('91', 'Clinton St & Washington Blvd'),
    ('283', 'LaSalle St & Jackson Blvd'),
    ('252', 'Greenwood Ave & 47th St'),
    ('186', 'Ogden Ave & Race Ave'),
    ('196', 'Cityfront Plaza Dr & Pioneer Ct'),
    ('141', 'Clark St & Lincoln Ave'),
    ('334', 'Lake Shore Dr & Belmont Ave'),
    ('166', 'Ashland Ave & Wrightwood Ave'),
    ('286', 'Franklin St & Quincy St'),
    ('308', 'Seeley Ave & Roscoe St'),
    ('128', 'Damen Ave & Chicago Ave'),
    ('77', 'Clinton St & Madison St'),
    ('50', 'Clark St & Congress Pkwy'),
    ('18', 'Wacker Dr & Washington St'),
    ('307', 'Southport Ave & Clybourn Ave'),
    ('325', 'Clark St & Winnemac Ave'),
    ('146', 'Loomis St & Jackson Blvd'),
    ('251', 'Clarendon Ave & Leland Ave'),
    ('492', 'Leavitt St & Addison St'),
    ('496', 'Avers Ave & Belmont Ave'),
    ('346', 'Ada St & Washington Blvd'),
    ('377', 'Kedzie Ave & Lake St'),
    ('163', 'Damen Ave & Clybourn Ave'),
    ('59', 'Wabash Ave & Roosevelt Rd'),
    ('347', 'Ashland Ave & Grace St'),
    ('111', 'Sedgwick St & Huron St'),
    ('340', 'Clark St & Wrightwood Ave'),
    ('143', 'Sedgwick St & Webster Ave'),
    ('75', 'Canal St & Jackson Blvd'),
    ('344', 'Ravenswood Ave & Lawrence Ave'),
    ('29', 'Noble St & Milwaukee Ave'),
    ('138', 'Clybourn Ave & Division St'),
    ('72', 'Wabash Ave & 16th St'),
    ('273', 'Michigan Ave & 18th St'),
    ('175', 'Wells St & Polk St'),
    ('123', 'California Ave & Milwaukee Ave'),
    ('48', 'Larrabee St & Kingsbury St'),
    ('183', 'Damen Ave & Augusta Blvd'),
    ('224', 'Halsted St & Willow St'),
    ('246', 'Ashland Ave & Belle Plaine Ave'),
    ('55', 'Halsted St & Roosevelt Rd'),
    ('99', 'Lake Shore Dr & Ohio St'),
    ('14', 'Morgan St & 18th St'),
    ('511', 'Albany Ave & Bloomingdale Ave'),
    ('86', 'Eckhart Park'),
    ('168', 'Michigan Ave & 14th St'),
    ('486', 'Oakley Ave & Irving Park Rd'),
    ('54', 'Ogden Ave & Chicago Ave'),
    ('284', 'Michigan Ave & Jackson Blvd'),
    ('327', 'Sheffield Ave & Webster Ave'),
    ('9', 'Leavitt St & Archer Ave'),
    ('67', 'Sheffield Ave & Fullerton Ave'),
    ('182', 'Wells St & Elm St'),
    ('195', 'Columbus Dr & Randolph St'),
    ('232', 'Pine Grove Ave & Waveland Ave'),
    ('255', 'Indiana Ave & Roosevelt Rd'),
    ('219', 'Damen Ave & Cortland St'),
    ('464', 'Damen Ave & Foster Ave'),
    ('319', 'Greenview Ave & Diversey Pkwy'),
    ('165', 'Clark St & Grace St'),
    ('311', 'Leavitt St & Lawrence Ave'),
    ('53', 'Wells St & Huron St'),
    ('426', 'Ellis Ave & 60th St'),
    ('107', 'Desplaines St & Jackson Blvd'),
    ('188', 'Greenview Ave & Fullerton Ave'),
    ('100', 'Orleans St & Merchandise Mart Plaza'),
    ('7', 'Field Blvd & South Water St'),
    ('230', 'Lincoln Ave & Roscoe St'),
    ('61', 'Wood St & Milwaukee Ave'),
    ('259', 'California Ave & Francis Pl'),
    ('264', 'Stetson Ave & South Water St'),
    ('45', 'Michigan Ave & Congress Pkwy'),
    ('292', 'Southport Ave & Clark St'),
    ('233', 'Sangamon St & Washington Blvd (*)'),
    ('69', 'Damen Ave & Pierce Ave'),
    ('47', 'State St & Kinzie St'),
    ('226', 'Racine Ave & Belmont Ave'),
    ('330', 'Lincoln Ave & Addison St'),
    ('199', 'Wabash Ave & Grand Ave'),
    ('289', 'Wells St & Concord Ln'),
    ('413', 'Woodlawn Ave & Lake Park Ave'),
    ('157', 'Lake Shore Dr & Wellington Ave'),
    ('161', 'Rush St & Superior St'),
    ('301', 'Clark St & Schiller St'),
    ('418', 'Ellis Ave & 53rd St'),
    ('342', 'Wolcott Ave & Polk St'),
    ('306', 'Sheridan Rd & Buena Ave'),
    ('211', 'St. Clair St & Erie St'),
    ('24', 'Fairbanks Ct & Grand Ave'),
    ('130', 'Damen Ave & Division St'),
    ('302', 'Sheffield Ave & Wrightwood Ave'),
    ('241', 'Morgan St & Polk St'),
    ('331', 'Halsted St & Blackhawk St (*)'),
    ('231', 'Sheridan Rd & Montrose Ave'),
    ('260', 'Kedzie Ave & Milwaukee Ave'),
    ('201', 'Indiana Ave & 40th St'),
    ('40', 'LaSalle St & Adams St'),
    ('154', 'Southport Ave & Belmont Ave'),
    ('276', 'California Ave & North Ave'),
    ('225', 'Halsted St & Dickens Ave'),
    ('88', 'May St & Randolph St'),
    ('81', 'Daley Center Plaza'),
    ('38', 'Clark St & Lake St'),
    ('116', 'Western Ave & Winnebago Ave'),
    ('93', 'Sheffield Ave & Willow St'),
    ('345', 'Lake Park Ave & 56th St'),
    ('28', 'Larrabee St & Menomonee St'),
    ('320', 'Loomis St & Lexington St'),
    ('44', 'State St & Randolph St'),
    ('94', 'Clark St & Armitage Ave'),
    ('5', 'State St & Harrison St'),
    ('41', 'Federal St & Polk St'),
    ('73', 'Jefferson St & Monroe St'),
    ('300', 'Broadway & Barry Ave'),
    ('177', 'Theater on the Lake'),
    ('149', 'Calumet Ave & 33rd St'),
    ('305', 'Western Ave & Division St'),
    ('468', 'Budlong Woods Library'),
    ('338', 'Calumet Ave & 18th St'),
    ('333', 'Ashland Ave & Blackhawk St'),
    ('140', 'Dearborn Pkwy & Delaware Pl'),
    ('238', 'Ravenswood Ave & Montrose Ave (*)'),
    ('288', 'Larrabee St & Armitage Ave'),
    ('176', 'Clark St & Elm St'),
    ('223', 'Clifton Ave & Armitage Ave'),
    ('13', 'Wilton Ave & Diversey Pkwy'),
    ('462', 'Ravenswood Ave & Balmoral Ave'),
    ('343', 'Racine Ave & Wrightwood Ave'),
    ('304', 'Broadway & Waveland Ave'),
    ('479', 'Drake Ave & Montrose Ave'),
    ('159', 'Claremont Ave & Hirsch St'),
    ('494', 'Kedzie Ave & Bryn Mawr Ave'),
    ('285', 'Wood St & Grand Ave'),
    ('178', 'State St & 19th St'),
    ('365', 'Halsted St & North Branch St'),
    ('500', 'Central Park Ave & Elbridge Ave'),
    ('366', 'Loomis St & Archer Ave'),
    ('213', 'Leavitt St & North Ave'),
    ('129', 'Blue Island Ave & 18th St'),
    ('23', 'Orleans St & Elm St (*)'),
    ('471', 'Francisco Ave & Foster Ave'),
    ('287', 'Franklin St & Monroe St'),
    ('268', 'Lake Shore Dr & North Blvd'),
    ('27', 'Larrabee St & North Ave'),
    ('108', 'Halsted St & Polk St'),
    ('158', 'Milwaukee Ave & Wabansia Ave'),
    ('299', 'Halsted St & Roscoe St'),
    ('313', 'Lakeview Ave & Fullerton Pkwy'),
    ('58', 'Marshfield Ave & Cortland St'),
    ('401', 'Shields Ave & 28th Pl'),
    ('205', 'Paulina St & 18th St'),
    ('25', 'Michigan Ave & Pearson St'),
    ('170', 'Clinton St & 18th St'),
    ('173', 'Mies van der Rohe Way & Chicago Ave'),
    ('339', 'Emerald Ave & 31st St'),
    ('329', 'Lake Shore Dr & Diversey Pkwy'),
    ('35', 'Streeter Dr & Grand Ave'),
    ('403', 'Wentworth Ave & 33rd St'),
    ('202', 'Halsted St & 18th St'),

project/mysite/myapp/forms.py
from django import forms  
from .models import Input, STATION

class InputForm(forms.ModelForm):  

    attrs = {'class ' : 'form−control ',
             'onchange ' : 'this.form.submit() '}

    station = forms.ChoiceField(choices=STATION, required=True,
                              widget=forms.Select(attrs = attrs))
    class Meta:

        model = Input
        fields = ['station']

project/mysite/myapp/views.py
#from .forms import InputForm
#from .models import STATES_DICT, CURRENCY_DICT

import geopandas as gpd, folium
from geopy import Nominatim

import seaborn as sns
sns.set(font_scale = 1.7)

from io import BytesIO

# Create your views here.
import matplotlib.pyplot as plt, numpy as np
import geopandas as gpd
import pandas as pd
import fiona
from shapely.geometry import Point
from os.path import join
from django.conf import settings
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from .forms import InputForm
from .models import STATION_DICT

def home(request):
    return render(request, "home.html", {"title": "Danger: Biking in Chicago"})

def map(request):
    return render(request, "map.html", {"title": "Map"})

def presentation(request):
    return render(request, "presentation.html", {"title": "Presentation"})

def about(request):
    return render(request, "about.html", {"title": "About"})


def csv(request, station = None):


   filename = join(settings.STATIC_ROOT, 'myapp/map_data.csv')

   df = pd.read_csv(filename)

   if station: df = df[df["station"] == int("Station ID")]

   table = df.to_html(float_format = "%.3f", classes = "table table-striped", index_names = False)
   table = table.replace('border="1"','border="0"')
   table = table.replace('style="text-align: right;"', "") # control this in css, not pandas.

   return HttpResponse(table)

def plot(request):

    station = request.GET.get('station', '')
    if not station: station = request.POST.get('station', '494')

    params = {'form_action' : reverse_lazy('myapp:plot'), 
              'form_method' : 'get', 
              'form' : InputForm({'station' : station}),
              'station' : STATION_DICT[station],
              "title" : "Divvy Crime Map",
              "pic_source" : reverse_lazy("myapp:pic", kwargs = {'station' : station})}

    return render(request, 'plot.html', params)

def pic(request, station = None):

   data_file = join(settings.STATIC_ROOT, 'myapp/join_data.csv')
   divvy_data = pd.read_csv(data_file)
   divvy_data = divvy_data[divvy_data["FROM STATION ID"] == int(station)]
   divvy_data['Type_Counts'] = divvy_data.groupby("Primary Type")["FROM STATION ID"].transform('count')
   result = divvy_data[["Primary Type","Type_Counts"]].drop_duplicates(keep='first')
   ax = result.plot(kind = "bar", legend = False, rot = 90, figsize=(40,15), x = "Primary Type", y = "Type_Counts")

   # write bytes instead of file.
   from io import BytesIO
   figfile = BytesIO()

   # this is where the color is used.
   try: ax.get_figure().savefig(figfile, format = 'png', bbox_inches='tight')
   except ValueError: raise Http404("No such color")

   figfile.seek(0) # rewind to beginning of file
   return HttpResponse(figfile.read(), content_type="image/png")

project/mysite/myapp/templates/about.html
{% extends "base.html" %}

{% block content %}

<div class="w3-container">
<div class="w3-content" style="max-width:800px">
  <h3 class="w3-center w3-padding-48"><span class="w3-tag w3-wide w3-padding-left w3-padding-right">Group Members</span></h3>
  <div class="w3-panel w3-leftbar w3-light-grey">
    <p>This site is developed by two graduate students from the University of Chicago.</p>
    <p>Ruochen Qiu</p>
    <p>Yanning Cui</p>
  </div>
</div>
</div>

<br>
<br>

  <img align="middle" src="http://www.magic4walls.com/wp-content/uploads/2013/12/Chicago-llinois-Willis-Tower-USA.jpg" class="w3-grayscale-min" alt="Downtown Chicago" width="100%" height="70%">

<br>
{% endblock %}

project/mysite/myapp/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster-src.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.Default.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.css" />
    <link rel="stylesheet" href="https://raw.githubusercontent.com/python-visualization/folium/master/folium/templates/leaflet.awesome.rotate.css" />

    <title>{{ title | default:"Danger: Biking in Chicago" }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">
</head>

<body>

<ul class="nav">
  <li><a href="{% url 'myapp:home' %}" class = "active">Introduction</a></li>
  <li><a href="{% url 'myapp:map' %}">Map</a></li>
  <li><a href="{% url 'myapp:plot' %}">Crime Data Analysis</a></li>
  <li><a href="{% url 'myapp:presentation' %}">Presentation</a></li>
  <li><a href="{% url 'myapp:about' %}">About</a></li>
</ul>

{% block content %}{% endblock %}
<div class="page-header"></div>
  <h3>
    <span class="label label-primary">Qiu</span>
    <span class="label label-success">Cui</span>
  </h3>


  <br>
  <br>
</body>
</html>

project/mysite/myapp/templates/home.html
{% extends "base.html" %}

{% block content %}

<header class="bgimg w3-display-container w3-grayscale-min">
  <div class="w3-display-bottomleft w3-center w3-padding-xlarge w3-hide-small">
    <span class="w3-tag">Check out crime data before you ride a bike</span>
  </div>
  <div class="w3-display-middle w3-center">
    <span class="w3-text-white" style="font-size:90px">Bike<br>And<br>Crime</span>
  </div>
  <div class="w3-display-bottomright w3-center w3-padding-xlarge">
    <span class="w3-text-white">Final Project, Nov 30, 2016</span>
  </div>
</header>
<br>
<br>
<p>
  <div class="w3-container">
  <div class="w3-content" style="max-width:800px">
    <h3 class="w3-center w3-padding-48"><span class="w3-tag w3-wide w3-padding-left w3-padding-right">What can you find here?</span></h3>
    <span class="w3-tag w3-xlarge w3-padding w3-right" style="transform:rotate(+5deg)">
      Danger!
    </span>
    <div class="w3-panel w3-leftbar w3-light-grey">
      <p>500+ bike stations in Chicago</p>
      <p>Crime data around any station in the city</p>
      <p>Just click on the map to see crime count information around each bike station in city of Chicago for the last 3 years.</p>
      <p>
        Find more about chicago crime dataset:
      <a href=https://data.cityofchicago.org/Public-Safety/Crimes-2016/kf95-mnd6>here</a>.
      <br>
      <p>
        Find more about Divvy dataset:
      <a href=https://data.cityofchicago.org/Transportation/Divvy-Trips-Dashboard/u94x-unre>here</a>.
    </div>
  </div>
</div>
{% endblock %}

project/mysite/myapp/templates/plot.html
{% extends "base.html" %}

{% block content %}
<br>
<br>

<form action="{{ form_action }}"
      method="{{ form_method }}">
  {% if form_method == "post" %}
    {% csrf_token %}
  {% endif %}

  {{ form.as_p }}
</form>

  <img src='{{ pic_source }}' width="80%" height="90%" align="middle">
 <br>
 <br>

<div class="w3-container" id="plot">
  <div class="w3-content" style="max-width:700px">

    <h5 class="w3-center w3-padding-48"><span class="w3-tag w3-wide w3-padding-left w3-padding-right">Data Analysis</span></h5>

    <div id="Data" class="w3-container menu w3-padding-48 w3-card-2">
      <h5>Primary Type</h5>
      <p class="w3-text-grey">The most common crime types are battery and theft.</</p><br>

      <h5>Traveling Tips</h5>
      <p class="w3-text-grey">Pay attention to your own belongings because theft occurs a lot in Chicago. When planning your trip, please check the plot around specific stations to avoid potential violent crimes including assault.</p><br>
    </div>
{% endblock %}

project/mysite/myapp/templates/presentation.html
{% extends "base.html" %}

{% block content %}

<div class="w3-container">
<div class="w3-content" style="max-width:800px">
  <h3 class="w3-center w3-padding-48"><span class="w3-tag w3-wide w3-padding-left w3-padding-right">Research Topic</span></h3>
  <div class="w3-panel w3-leftbar w3-light-grey">
    <p>Our topic is about crimes around each bike station in Chicago area. </p>
    <p>We want to make a web app where you can find how many crimes around any bike station in the map, and you can check the types and counts of crimes! </p>
  </div>
</div>
</div>

<div class="w3-container">
<div class="w3-content" style="max-width:800px">
  <h3 class="w3-center w3-padding-48"><span class="w3-tag w3-wide w3-padding-left w3-padding-right">Data Sources and Data Clean</span></h3>
  <div class="w3-panel w3-leftbar w3-light-grey">
    <p>There are two main data sources:</p>
    <p>First one is the divvy data, this gives us geometirc information of all bike stations in the city. For the divvy data, I selected the latest data from Ferb 1st to July 1st to count the stations. From it, I picked three columns "FROM STATION ID","FROM LONGITUDE","FROM LATITUDE", kept every new station while dropped the duplicate stations. The result shows that there are 524 stations been used recently. Then we transferred this station data into a geo data-frame.</p>
    <p>The second one is crime data, we used all crime data staring from 2013 till now. For the crime data, we picked Primary Type, Longitude and Latitude column to make a list of tuple as location points and transferred them into a geo data-frame as we did with divvy data.</p>
  </div>
</div>
</div>

<div class="w3-container">
<div class="w3-content" style="max-width:800px">
  <h3 class="w3-center w3-padding-48"><span class="w3-tag w3-wide w3-padding-left w3-padding-right">How we merge data</span></h3>
  <div class="w3-panel w3-leftbar w3-light-grey">
    <p>We set divvy points radian (300 meters) and join with crime data points, save the intermediate join data as join_data.csv, and used this for the website map and plot.</p>
  </div>
</div>
</div>

<div class="w3-container">
<div class="w3-content" style="max-width:800px">
  <h3 class="w3-center w3-padding-48"><span class="w3-tag w3-wide w3-padding-left w3-padding-right">Mapping</span></h3>
  <div class="w3-panel w3-leftbar w3-light-grey">
    <p>After merging to get a complete data frame (“maps”) folium is imported for actual mapping. A “for” loop is used for each row in the “maps” data frame, and the html and Iframe functions in folium are used to create popup labels on markers, each of which indicates a bike station. The popup labels provide information on station name, station ID, and the number of crimes that have occurred in a 300 meter radius around that station in the past three years. </p>
  </div>
</div>
</div>

<div class="w3-container">
<div class="w3-content" style="max-width:800px">
  <h3 class="w3-center w3-padding-48"><span class="w3-tag w3-wide w3-padding-left w3-padding-right">Plot Crime Type around the station</span></h3>
  <div class="w3-panel w3-leftbar w3-light-grey">
    <p>In our website, under "Crime Data Analysis" tab, you can find the plot of crimes near any station you choose under the dropdown menu. The crime plot has information of types of crimes occurred near the station you chose, also the number of crimes.</p>
    <p>Using this information, you can avoid areas that are more dangerous when you plan your trip.</p>
  </div>
</div>
</div>

<br>
{% endblock %}